//Maps to pins of CNC shield
#define MOTORS_ENABLE PORT_PA06
#define STEP_MOTOR_1  PORT_PA08
#define DIR_MOTOR_1   PORT_PA21
#define STEP_MOTOR_2  PORT_PA09
#define DIR_MOTOR_2   PORT_PA20
#define STEP_MOTOR_3  PORT_PA14
#define DIR_MOTOR_3   PORT_PA15
#define SERVO_1       PORT_PA16
#define SERVO_2       PORT_PA18
#define ELECTROMAGNET PORT_PA07

//#define MOTORS_ENABLE()  REG_PORT_OUTSET0 |= PORT_PA16
//#define STEP_MOTOR_1()  REG_PORT_OUTSET0 |= PORT_PA15
//#define DIR_MOTOR_1()   REG_PORT_OUTSET0 |= PORT_PA20
//#define STEP_MOTOR_2()  REG_PORT_OUTSET0 |= PORT_PA21
//#define DIR_MOTOR_2()  REG_PORT_OUTSET0 |= PORT_PA06
//#define STEP_MOTOR_3()  REG_PORT_OUTSET0 |= PORT_PA07
//#define DIR_MOTOR_3()  REG_PORT_OUTSET0 |= PORT_PA18
//#define SERVO_1()  REG_PORT_OUTSET0 |= PORT_PA09
//#define SERVO_2()  REG_PORT_OUTSET0 |= PORT_PA08
//#define ELECTROMAGNET()  REG_PORT_OUTSET0 |= PORT_PA19
